; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev_ota

[env:esp32dev_ota]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.partitions = partitions_heater.csv
board_build.filesystem = littlefs
upload_protocol = espota
upload_port = 192.168.178.50
upload_flags = 
	--port=3232
	--timeout=600
	--progress
build_flags = 
	-Wall
	-DCORE_DEBUG_LEVEL=1
lib_ignore = 
	WiFiNINA_-_Adafruit_Fork
	WiFi101
	WiFiNINA
lib_deps = 
	knolleary/PubSubClient @ ^2.8
	bblanchon/ArduinoJson
	luisllamasbinaburo/InterpolationLib @ ^1.0.2
	DFRobot/DFRobot_GP8XXX @ 1.0.1
	hoeken/PsychicHttp @ ^1.2.1
	paulstoffregen/OneWire @ ^2.3.7
	milesburton/DallasTemperature @ ^3.11.0

[env:esp32dev_serial]
extends = env:esp32dev_ota
upload_protocol = esptool
upload_port = /dev/cu.wchusbserial1230
upload_speed = 460800
upload_flags = 

[env:esp32dev_ota_lan]
extends = env:esp32dev_ota
upload_protocol = espota
upload_port = 192.168.178.64
upload_flags = 
	--port=3232
	--timeout=600
	--progress
