[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions.csv

lib_deps =
  knolleary/PubSubClient
  bblanchon/ArduinoJson @ ^6
  paulstoffregen/OneWire
  milesburton/DallasTemperature
  adafruit/Adafruit SHT31 Library
  adafruit/Adafruit Unified Sensor
  me-no-dev/AsyncTCP
  esphome/ESPAsyncWebServer-esphome

build_flags =
  -DCORE_DEBUG_LEVEL=1


[env:esp32ota]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions.csv

; OTA upload using ArduinoOTA / espota.py
upload_protocol = espota
upload_port = 192.168.178.60
upload_flags = 
  --progress

lib_deps =
  knolleary/PubSubClient
  bblanchon/ArduinoJson @ ^6
  paulstoffregen/OneWire
  milesburton/DallasTemperature
  adafruit/Adafruit SHT31 Library
  adafruit/Adafruit Unified Sensor
  me-no-dev/AsyncTCP
  esphome/ESPAsyncWebServer-esphome

build_flags =
  -DCORE_DEBUG_LEVEL=1
